---
title: "iteration_and_listcols"
author: "Matthew Lawlor"
date: "11/17/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(rvest)

set.seed(1)
```

## lists

You can put anything in a list

```{r}
l = list(
  vec_numeric = 5:8,
  vec_logical = c(TRUE, TRUE, FALSE, TRUE, FALSE, FALSE),
  mat = matrix(1:8, nrow =2, ncol = 4),
  summary = summary(rnorm(100))
)
```

```{r}
l
l$vec_numeric
l[[1]] ##first list element
mean(l[["vec_numeric"]])
l[["vec_numeric"]][1:3]
```

## `for` loop

create a new list

```{r}
list_norm = 
  list(
    a = rnorm(20, mean =3, sd =1),
    b = rnorm(30, mean =0, sd =5),
    c = rnorm(40, mean =10, sd =0.2),
    d = rnorm(20, mean =-3, sd =1)
  )
```

```{r}
list_norm[[1]]
```

Pause and get my old function

```{r}
mean_and_sd = function(x) {
  
  if (!is.numeric(x)) {
    stop("Argument x should be numeric")
  } else if (length(x) == 1) {
    stop("Cannot be computed for length 1 vectors")
  }
  
  mean_x = mean(x)
  sd_x = sd(x)

  tibble(
    mean = mean_x, 
    sd = sd_x
  )
}
```

I can apply that function to each list element

```{r}
mean_and_sd (list_norm[[1]])
mean_and_sd (list_norm[[2]])
mean_and_sd (list_norm[[3]])
mean_and_sd (list_norm[[4]])
```

Let's use a `for` loop

```{r}
output = vector("list", length = 4)

for (i in 1:4) {

  output[[i]] = mean_and_sd(list_norm[[i]])

}
```

