---
title: "simulation"
author: "Matthew Lawlor"
date: "11/18/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
library(tidyverse)
library(rvest)

set.seed(1)
```


## Let's simulate something

Here is a function

```{r}
sim_mean_sd = function(n, mu = 2, sigma = 3) {
  
  sim_data = tibble(
    x = rnorm(n, mean = mu, sd = sigma),
  )
  
  sim_data %>% 
    summarize(
      mean = mean(x),
      sd = sd(x)
    )
}
```

I can "simulate" by running this line

```{r}
sim_mean_sd(30)
```

## Let's simulate a lot

We'll start with a for loop

```{r}
output = vector("list", length = 100)

for (i in 1:100) {
  
  output[[i]] = sim_mean_sd(n = 30)
  
}

bind_rows(output)
```


Let's use a loop function from purr instead

```{r}
sim_results = 
  rerun(100, sim_mean_sd(n = 30)) %>% 
  bind_rows()
```

Let's look at results

```{r}
sim_results %>% 
  ggplot(aes(x = mean)) + geom_density()

sim_results %>% 
  summarize(
    avg_samp_mean = mean(mean),
    sd_samp_mean = sd(mean)
  )

sim_results %>% 
  ggplot(aes(x = sd)) + geom_density()
```


## Let's try other sample sizes

```{r}
n_list =
  list(
    "n = 30" = 30,
    "n = 60" = 60,
    "n = 120" = 120,
    "n = 240" = 240
  )

output = vector("list", length = 4)

output[[1]] = rerun(100, sim_mean_sd(n = n_list[[1]])) %>% bind_rows
output[[2]] = rerun(100, sim_mean_sd(n = n_list[[2]])) %>% bind_rows

for(i in 1:4){
  
  output[[i]] = 
    rerun(100, sim_mean_sd(n = n_list[[i]])) %>% 
    bind_rows()
}
```

Create a tibble

```{r, cache = TRUE}
##cache saves this output so it doesn't rerun every time I knit
sim_results = 
  tibble(
    sample_size = c(30, 60, 120, 240)
  ) %>% 
  mutate(
    output_lists = map(.x = sample_size, ~ rerun(1000, sim_mean_sd(.x))),
    estimate_df = map(output_lists, bind_rows)
  ) %>% 
  select(-output_lists) %>% 
  unnest(estimate_df)
```

Now we can do some dataframe things, like plotting!

```{r}
sim_results %>% 
  mutate(
    sample_size = str_c("n = ", sample_size),
    sample_size = fct_inorder(sample_size)
  ) %>% 
  ggplot(aes(x = sample_size, y = mean)) +
  geom_violin()
```

```{r}
sim_results %>% 
  group_by(sample_size) %>% 
  summarize(
  avg_samp_mean = mean(mean),
  sd_samp_mean = sd(mean)
  )
```

