---
title: "writing_functions"
author: "Matthew Lawlor"
date: "11/13/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(rvest)
```

```{r}
set.seed(1)
```

## Do something simple

```{r}
x_vec = rnorm(30, mean = 5, sd = 3)

(x_vec - mean(x_vec)) / sd(x_vec)##computes a z-score
```

I want a function to compute z-scores

```{r}
z_scores = function(x) {

 if(!is.numeric(x)) {
   stop("Input must be numeric")
 }
   
 if(length(x) < 3) {
   stop("Must have at least three numbers")
 }
  
 z = (x - mean(x)) / sd(x)
  
  return(z)
  
}

z_scores(x_vec)
```

Try my function on some other things. These should give errors!

```{r, error = TRUE}
z_scores(3)
z_scores("my name is matt")
z_scores(mtcars)
z_scores(c(TRUE, TRUE, FALSE, TRUE))
```

## Multiple outputs

```{r}
mean_and_sd = function(x) {

 if(!is.numeric(x)) {
   stop("Input must be numeric")
 }
   
 if(length(x) < 3) {
   stop("Must have at least three numbers")
 }
  
 mean_x = mean(x)
 sd_x = sd(x)
  
 tibble(##instead of return, can also use list
   mean = mean_x,
   sd = sd_x
   )
  
}
```

Check that the function works.

```{r}
mean_and_sd(x_vec)
```

## Multiple inputs

I'd like to do this with a function
```{r}
sim_data = 
  tibble(
    x = rnorm(100, mean = 4, sd = 3)
  )

sim_data %>% 
  summarize(
  mean = mean(x),
  sd = sd(x)
  )
```

The function
```{r}
sim_mean_sd = function(samp_size, mu, sigma) {
  
  sim_data = 
    tibble(
      x = rnorm(n = samp_size, mean = mu, sd =        sigma)
  )

  sim_data %>% 
  summarize(
  mean = mean(x),
  sd = sd(x)
  )
  
}

sim_mean_sd(100, 6, 3)
```

